module.exports = {
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/apps/api-e2e',
    '<rootDir>/libs/api/data-access-auth',
    '<rootDir>/libs/api/feature-auth',
    '<rootDir>/libs/api/data-access-core',
    '<rootDir>/libs/api/feature-core',
    '<rootDir>/apps/app',
    '<rootDir>/libs/app/assets',
    '<rootDir>/libs/app/data-access-core',
    '<rootDir>/libs/app/feature-about',
    '<rootDir>/libs/app/feature-core',
    '<rootDir>/libs/app/feature-dashboard',
    '<rootDir>/libs/app/feature-shell',
    '<rootDir>/libs/app/layout',
    '<rootDir>/libs/app/style',
    '<rootDir>/libs/app/feature-auth',
    '<rootDir>/libs/app/ui/form-checkbox',
  ],
}
